import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

<<<<<<< Updated upstream
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
=======
import CustomCursor from "@/components/ui/custom-cursor";
import SplashCursor from "@/components/ui/splash-cursor";
import LenisProvider from "@/providers/lenis-provider";
>>>>>>> Stashed changes

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          {`
            @import url('https://fonts.googleapis.com/css2?family=Google+Sans:ital,opsz,wght@0,17..18,400..700;1,17..18,400..700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap');
          `}
        </style>
      </head>
<<<<<<< Updated upstream
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
      <body className="font-sans antialiased">
        <LenisProvider>
          <SplashCursor />
          <CustomCursor />
          {children}
        </LenisProvider>
>>>>>>> Stashed changes
      </body>
    </html>
  );
}
